const fs=require('fs'),ts=require('typescript'),vm=require('vm'),assert=require('node:assert/strict');
const cache={};function load(name){if(cache[name])return cache[name];const module={exports:{}};const js=ts.transpileModule(fs.readFileSync('lib/'+name+'.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(js,{module,exports:module.exports,require:p=>load(p.replace('./','')),URL,Date,Error,Number,Set});return cache[name]=module.exports;}
const {driveFile,validateAssetLink}=load('assets'),{validatePost,seedPosts}=load('marketing'),{postToRow,normalizePost,postFields}=load('post-storage');
const url='https://drive.google.com/file/d/file_123/view?resourcekey=key123';
assert.equal(driveFile(url).download,'https://drive.google.com/uc?export=download&id=file_123&resourcekey=key123');
assert.equal(driveFile('https://drive.google.com/open?id=abc').preview,'https://drive.google.com/file/d/abc/preview');
for(const bad of ['javascript:alert(1)','https://drive.google.com.evil.com/file/d/x/view','https://drive.google.com/drive/folders/abc'])assert.throws(()=>validateAssetLink(bad));
const seed=seedPosts()[0];assert.equal(validatePost({...seed,completedAt:new Date().toISOString()}).completedAt!==null,true);
const done=validatePost({...seed,assetUrl:url,assetType:'video',coverUrl:'https://drive.google.com/file/d/cover/view',imageTwoUrl:'https://drive.google.com/file/d/image-two/view',completedAt:'2026-09-27T05:00:00Z'});
assert.equal(done.status,'Planned');assert.equal(done.completedAt,'2026-09-27T05:00:00Z');
const row=postToRow(done);assert.equal(row.asset_url,url);assert.equal(row.image_two_url,done.imageTwoUrl);assert.equal(row.completed_at,done.completedAt);assert.equal(row.posted_time,null);assert.equal(row.contentType,undefined);assert.ok(postFields.includes('imageTwoUrl:image_two_url'));assert.equal(normalizePost({...done,postedTime:'12:30:00'}).postedTime,'12:30');assert.equal(normalizePost({...done,postedTime:null}).postedTime,'');
console.log('PASS: Drive links, resource keys, unsafe/folder URL rejection, Done validation, publication independence, and database round-trip fields.');
const {accountName,staffNameMatches,entryIdentity,manilaTimestamp,daysBefore}=load('entry-details');
assert.equal(accountName('ella',['Ella','Reg']),'Ella');
assert.equal(accountName('reginajoycamasis',['Ella','Reg']),'Reg');
assert.equal(staffNameMatches('reginajoycamasis','Reg'),true);
assert.equal(daysBefore('2026-09-30',2),'2026-09-28');
assert.equal(validatePost({...seed,delayReason:'Late asset handoff'}).delayReason,'Late asset handoff');
const {teamKpi}=load('kpi');
const regKpi=teamKpi([{...seed,owners:['reginajoycamasis'],date:'2026-09-28',platform:'TikTok',format:'Reel',status:'Published'},{...seed,id:'reg-2',owners:['reginajoycamasis'],date:'2026-09-29',platform:'Facebook',format:'Reel',status:'Published'}],'Reg','2026-09-28');
assert.equal(regKpi.published,2);assert.equal(regKpi.done,2);
const identity=entryIdentity(undefined,'ella-uid','Ella','Planned',false,'2026-09-27T05:00:00Z');assert.equal(identity.owners[0],'Ella');assert.equal(identity.createdBy,'ella-uid');
const edited=entryIdentity({...identity,owners:['Ella']},'reg-uid','Reg','For posting',true,'2026-09-27T06:00:00Z');assert.equal(edited.owners[0],'Ella');assert.equal(edited.createdBy,'ella-uid');assert.equal(edited.createdAt,identity.createdAt);assert.equal(edited.completedAt,'2026-09-27T06:00:00Z');
const caption='New PC build ✨🔥\nReady na! 🖥️';const entry=validatePost({...seed,caption,status:'For posting'});assert.equal(postToRow(entry).caption,caption);assert.match(manilaTimestamp('2026-09-27T05:15:00Z'),/1:15 PM/);assert.equal(normalizePost({...done,postedTime:'8:00 PM'}).postedTime,'20:00');
console.log('PASS: server-derived owner, edit identity preservation, emoji caption, For posting status, AM/PM Manila timestamp.');
assert.throws(()=>validatePost({...seed,assetUrl:url,status:'Published',completedAt:'2026-09-27T05:00:00Z',url:''}));
assert.throws(()=>validatePost({...seed,assetUrl:url,status:'Published',completedAt:'2026-09-27T05:00:00Z',url:'https://example.com/post'}));
assert.equal(validatePost({...seed,assetUrl:url,status:'Published',completedAt:'2026-09-27T05:00:00Z',url:'https://www.tiktok.com/@pchub/video/123'}).status,'Published');
console.log('PASS: Done publication requires a valid platform link.');
