"use client";
import {useEffect,useRef,useState} from 'react';
import {LayoutDashboard,CalendarDays,ChartNoAxesCombined,Users,Monitor,Plus,ArrowUpRight,ChevronLeft,ChevronRight,Clapperboard,Check,Link2,X,ArrowRight,RefreshCw,Search,LogOut} from 'lucide-react';
import {Post,staff as initialStaff,statuses,contentTypes,validatePost} from '../lib/marketing';
import {teamKpi} from '../lib/kpi';
import {getBrowserSupabaseClient,hasSupabaseConfig} from '../lib/supabase';
const sections=['Overview','Posting Monitoring','Calendar','Analytics','Team KPI'];
const icons=[LayoutDashboard,Clapperboard,CalendarDays,ChartNoAxesCombined,Users];
const fmt=(n:number)=>new Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(n);
function Avatar({name}:{name:string}){return <span className={'avatar '+name.toLowerCase()} title={name}>{name[0]}</span>}
function Platform({name}:{name:string}){return <span className={'platform '+name.toLowerCase()}>{name==='Facebook'?'f':'♪'}</span>}
export default function Dashboard(){
 const [view,setView]=useState('Overview'),[posts,setPosts]=useState<Post[]>([]),[staff,setStaff]=useState<string[]>(initialStaff),[loading,setLoading]=useState(true),[error,setError]=useState(''),[platform,setPlatform]=useState('All platforms'),[person,setPerson]=useState('All members'),[query,setQuery]=useState(''),[week,setWeek]=useState('2026-09-21'),[edit,setEdit]=useState<Post|null>(null),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[userName,setUserName]=useState(''),[selected,setSelected]=useState<string[]>([]);
 const supabase=getBrowserSupabaseClient();
 const dialog=useRef<HTMLDialogElement>(null);
 const authorizedFetch=async(path:string,init:RequestInit={})=>{const {data}=await supabase.auth.getSession();const headers=new Headers(init.headers);if(data.session?.access_token)headers.set('Authorization',`Bearer ${data.session.access_token}`);return fetch(path,{...init,headers});};
 const load=async()=>{setLoading(true);try{if(!hasSupabaseConfig()){setPosts([]);setError('');return}const [postsResponse,teamResponse]=await Promise.all([authorizedFetch('/api/posts'),authorizedFetch('/api/team')]);const d=await postsResponse.json() as Post[] & {error?:string};if(!postsResponse.ok)throw Error(d.error);if(teamResponse.ok)setStaff(await teamResponse.json() as string[]);setPosts(d);setError('');}catch(e){setError((e as Error).message);}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 useEffect(()=>{supabase.auth.getUser().then(({data})=>setUserName(data.user?.email??''));},[supabase]);
 useEffect(()=>{if(edit)dialog.current?.showModal();else dialog.current?.close()},[edit?.id]);
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:Function}}).modelContext;if(!context?.registerTool)return;const control=new AbortController();try{Promise.resolve(context.registerTool({name:'navigate_marketing_workspace',description:'Open a marketing workspace view. Does not modify records.',inputSchema:{type:'object',properties:{view:{type:'string',enum:sections}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:{view:string})=>{if(!sections.includes(input.view))throw Error('Unknown view');setView(input.view);return {view:input.view}}},{signal:control.signal})).catch(()=>{});}catch{}return()=>control.abort()},[]);
 const end=new Date(week+'T12:00:00');end.setDate(end.getDate()+6);const endstr=end.toISOString().slice(0,10);
 const inWeek=posts.filter(p=>p.date>=week&&p.date<=endstr);
 const filtered=inWeek.filter(p=>(platform==='All platforms'||p.platform===platform)&&(person==='All members'||p.owners.includes(person))&&p.title.toLowerCase().includes(query.toLowerCase()));
 const published=filtered.filter(p=>p.status==='Published');
 const sum=(key:'views'|'likes'|'comments'|'shares')=>published.reduce((s,p)=>s+(p[key]??0),0);
 const days=Array.from({length:7},(_,i)=>{const d=new Date(week+'T12:00:00');d.setDate(d.getDate()+i);return d});
 const moveWeek=(n:number)=>{const d=new Date(week+'T12:00:00');d.setDate(d.getDate()+n*7);setWeek(d.toISOString().slice(0,10))};
 const newPost=()=>{setMessage('');setEdit({id:crypto.randomUUID(),title:'',contentType:'Entertainment',platform:'Facebook',format:'Reel',owners:staff.slice(0,1),date:week,postedTime:'',status:'Planned',url:'',views:null,likes:null,comments:null,shares:null})};
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!edit)return;setSaving(true);setMessage('');try{validatePost(edit);if(!hasSupabaseConfig()){setPosts(prev=>[...prev.filter(p=>p.id!==edit.id),edit]);setEdit(null);return}const r=await authorizedFetch('/api/posts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(edit)});const d=await r.json() as Post & {error?:string};if(!r.ok)throw Error(d.error);setPosts(prev=>[...prev.filter(p=>p.id!==d.id),d]);setEdit(null);}catch(e){setMessage((e as Error).message)}finally{setSaving(false)}};
 const isAdmin=userName.startsWith('admin@');
 const openPost=(p:Post)=>{if(p.status==='Published'&&!isAdmin){window.alert('Published posts are locked. Only an admin can edit them.');return}setMessage('');setEdit({...p,owners:[...p.owners]})};
 const range=days[0].toLocaleDateString('en',{month:'short',day:'numeric'})+' – '+end.toLocaleDateString('en',{day:'numeric',month:'short',year:'numeric'});
 const memberKpi=(name:string)=>teamKpi(posts,name,week);
 const removePost=async(p:Post)=>{if(!window.confirm(`Delete “${p.title}”?`))return;try{const r=await authorizedFetch(`/api/posts?id=${encodeURIComponent(p.id)}`,{method:'DELETE'});if(!r.ok){const d=await r.json() as {error?:string};throw Error(d.error)}setPosts(prev=>prev.filter(x=>x.id!==p.id));setSelected(prev=>prev.filter(id=>id!==p.id));}catch(e){window.alert((e as Error).message)}};
 const deleteSelected=async()=>{if(!selected.length||!window.confirm(`Delete ${selected.length} selected posts?`))return;try{const results=await Promise.all(selected.map(id=>authorizedFetch(`/api/posts?id=${encodeURIComponent(id)}`,{method:'DELETE'})));const failed=results.find(r=>!r.ok);if(failed){const d=await failed.json() as {error?:string};throw Error(d.error)}setPosts(prev=>prev.filter(p=>!selected.includes(p.id)));setSelected([]);}catch(e){window.alert((e as Error).message)}};
 const addStaff=async()=>{const name=window.prompt('Staff name');if(!name?.trim())return;try{const r=await authorizedFetch('/api/team',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})});const d=await r.json() as {name?:string;error?:string};if(!r.ok)throw Error(d.error);setStaff(prev=>[...prev,d.name!].sort());}catch(e){window.alert((e as Error).message)}};
 const removeStaff=async(name:string)=>{if(!window.confirm(`Remove ${name} from the team? Existing post records will remain.`))return;try{const r=await authorizedFetch(`/api/team?name=${encodeURIComponent(name)}`,{method:'DELETE'});if(!r.ok){const d=await r.json() as {error?:string};throw Error(d.error)}setStaff(prev=>prev.filter(x=>x!==name));}catch(e){window.alert((e as Error).message)}};
 const table=(rows:Post[])=><div className="tablewrap"><table><thead><tr>{isAdmin&&<th><input aria-label="Select all posts" type="checkbox" checked={rows.length>0&&rows.every(p=>selected.includes(p.id))} onChange={e=>setSelected(e.target.checked?[...new Set([...selected,...rows.map(p=>p.id)])]:selected.filter(id=>!rows.some(p=>p.id===id)))}/></th>}<th>PLATFORM</th><th>DATE & TIME</th><th>TYPE</th><th>CONTENT</th><th>POSTED BY</th><th>STATUS</th>{isAdmin&&<th>ACTIONS</th>}</tr></thead><tbody>{rows.map(p=><tr key={p.id} onClick={()=>openPost(p)}>{isAdmin&&<td><input aria-label={`Select ${p.title}`} type="checkbox" checked={selected.includes(p.id)} onClick={e=>e.stopPropagation()} onChange={e=>setSelected(prev=>e.target.checked?[...prev,p.id]:prev.filter(id=>id!==p.id))}/></td>}<td><span className="inline"><Platform name={p.platform}/>{p.platform}</span></td><td>{new Date(p.date+'T12:00:00').toLocaleDateString('en',{month:'short',day:'numeric'})}{p.postedTime&&<small>{p.postedTime}</small>}</td><td>{p.contentType}</td><td><button className="titlebutton" onClick={e=>{e.stopPropagation();openPost(p)}}>{p.title}</button><small>{p.format}</small></td><td><span className="avatars">{p.owners.map(n=><Avatar key={n} name={n}/>)}</span><small>{p.owners.join(', ')}</small></td><td><span className={'badge '+p.status.toLowerCase().replaceAll(' ','-')}>{p.status}</span></td>{isAdmin&&<td><span className="admin-actions"><button className="secondary" onClick={e=>{e.stopPropagation();openPost(p)}}>Edit</button><button className="secondary" onClick={e=>{e.stopPropagation();removePost(p)}}>Delete</button></span></td>}</tr>)}</tbody></table>{!rows.length&&<div className="empty">No posts in this view. Add a post to start monitoring.</div>}</div>;
 return <div className="shell"><aside><a className="brand" href="/" aria-label="PC Hub"><span className="pchub-logo"/></a><div className="workspace"><span className="workspaceicon">M</span><div>Digital Marketing<small>PC Hub Philippines</small></div></div><p className="navlabel">WORKSPACE</p><nav>{sections.map((s,i)=>{const Icon=icons[i];return <button key={s} className={view===s?'active':''} onClick={()=>{setView(s);setQuery('')}}><Icon size={19}/>{s}{s==='Posting Monitoring'&&<span className="navcount">{posts.length}</span>}</button>})}</nav><div className="sidebottom"><div className="sidecallout"><span className="tinylabel">ONE TEAM. ONE WORKSPACE.</span><p>Good content starts<br/>with a clear plan.</p><span className="avatars">{staff.map(n=><Avatar name={n} key={n}/>)}</span><small>3 marketing teammates</small></div><div className="profile"><span className="profileicon">PC</span><div>Marketing Team<small>PC Hub workspace</small></div></div></div></aside>
 <div className="main"><header><span className="breadcrumb">Workspace <span>/</span> <strong>{view}</strong></span><div className="headerend"><span className="muted">Manila time · UTC+8</span><span className="signed-user" title={userName}>{userName}</span><button className="logout" onClick={async()=>{await supabase.auth.signOut();window.location.assign('/login')}} aria-label="Sign out"><LogOut size={16}/></button><span className="profileicon">PC</span></div></header><main><div className="heading"><div><div className="eyebrow">PC HUB / DIGITAL MARKETING</div><h1>{view==='Overview'?'Your marketing, in one place.':view}</h1><p>{view==='Overview'?'Plan the content. Keep the team aligned. Track what matters.':view==='Calendar'?'A shared content plan for every channel and every teammate.':view==='Analytics'?'Performance from published posts and manually recorded metrics.':view==='Team KPI'?'Weekly delivery against each teammate’s assigned posts.':'Keep every post moving from the plan to publication.'}</p></div><button className="primary" onClick={newPost} disabled={loading||!!error}><Plus size={18}/> Add post</button></div>
 <div className="toolbar"><div className="weekpicker"><CalendarDays size={17}/><span>{range}</span><button aria-label="Previous week" onClick={()=>moveWeek(-1)}><ChevronLeft size={16}/></button><button aria-label="Next week" onClick={()=>moveWeek(1)}><ChevronRight size={16}/></button></div><div className="filters">{view!=='Team KPI'&&<><select aria-label="Platform filter" value={platform} onChange={e=>setPlatform(e.target.value)}>{['All platforms','Facebook','TikTok'].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Member filter" value={person} onChange={e=>setPerson(e.target.value)}>{['All members',...staff].map(x=><option key={x}>{x}</option>)}</select></>}<button className="refresh" aria-label="Refresh workspace" onClick={load}><RefreshCw size={17}/></button></div></div>
 {error?<div className="error">{error} <button onClick={load}>Retry</button></div>:loading?<div className="empty">Loading shared workspace…</div>:<>
 {view==='Overview'&&<><div className="quickgrid">{['Posting Monitoring','Calendar','Analytics','Team KPI'].map((s,i)=>{const Icon=icons[i+1];return <button className={'quick q'+i} key={s} onClick={()=>setView(s)}><div className="quicktop"><span className="quickicon"><Icon size={21}/></span><ArrowUpRight size={18}/></div><h3>{s}</h3><div className="quickvalue">{i===0?<>{published.length}<span> / {filtered.length}</span></>:i===1?filtered.length:i===2?(published.some(p=>p.views!==null)?fmt(sum('views')):'—'):'03'}<small>{['posts published','posts this week','recorded views','team members'][i]}</small></div><div className="quickfoot">{['Stay on top of every post','See the weekly content plan','Understand your performance','Make every contribution count'][i]} <ArrowRight size={15}/></div></button>})}</div>
 <div className="twocol"><section className="panel"><div className="sectionhead"><div><h2>Latest published posts</h2><p>Your most recent recorded content, by platform</p></div><span className="pill">Manual tracking</span></div><div className="latestgrid">{['Facebook','TikTok'].map(channel=>{const latest=posts.filter(p=>p.platform===channel&&p.status==='Published').sort((a,b)=>b.date.localeCompare(a.date))[0];return <div className="channelcard" key={channel}><div className="channelhead"><span className="inline"><Platform name={channel}/><strong>{channel}</strong></span><span className="muted">{channel==='Facebook'?'@pchub':'Handle pending'}</span></div>{latest?<><h3>{latest.title}</h3><p>{latest.date} · {latest.owners.join(', ')}</p><a className="textlink" href={latest.url} target="_blank" rel="noreferrer">View post <ArrowUpRight size={15}/></a></>:<div className="channelblank"><Clapperboard size={27}/><strong>No published posts yet</strong><p>Add a post link once your content is live.</p></div>}<div className="channelmeta"><span>Automatic sync not connected</span>{channel==='Facebook'&&<a href="https://www.facebook.com/pchub" target="_blank" rel="noreferrer" aria-label="Open PC Hub Facebook page"><ArrowUpRight size={16}/></a>}</div></div>})}</div></section><section className="panel teammini"><div className="sectionhead"><div><h2>Team pulse</h2><p>This week’s posting progress</p></div><Users size={19}/></div>{staff.map(name=>{const k=memberKpi(name);return <div className="member" key={name}><div className="memberrow"><span className="inline"><Avatar name={name}/><strong>{name}</strong></span><span>{k.done}<span className="muted"> / {k.assigned}</span></span></div><div className="progress"><span style={{width:(k.assigned?k.done/k.assigned*100:0)+'%'}}/></div></div>})}<button className="textlink" onClick={()=>setView('Team KPI')}>View team performance <ArrowRight size={16}/></button></section></div>
 <section className="panel"><div className="sectionhead"><div><h2>On the content board <span className="count">{filtered.filter(p=>p.status!=='Published').length}</span></h2><p>Upcoming work from your weekly plan</p></div><button className="textlink" onClick={()=>setView('Posting Monitoring')}>View all posts <ArrowRight size={16}/></button></div>{table(filtered.filter(p=>p.status!=='Published').sort((a,b)=>a.date.localeCompare(b.date)).slice(0,5))}</section></>}
 {view==='Posting Monitoring'&&<><div className="statusgrid">{statuses.map(s=><div className="stat" key={s}><span>{s}</span><strong>{filtered.filter(p=>p.status===s).length}</strong></div>)}</div><section className="panel"><div className="sectionhead"><h2>All content <span className="count">{filtered.length}</span></h2><div className="inline">{isAdmin&&<><button className="secondary" onClick={()=>setSelected([...filtered.map(p=>p.id)])}>Edit table</button><button className="secondary" disabled={!selected.length} onClick={deleteSelected}>Delete selected ({selected.length})</button></>}<label className="search"><Search size={16}/><input aria-label="Search content" placeholder="Search content…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div></div>{table([...filtered].sort((a,b)=>a.date.localeCompare(b.date)))}</section></>}
 {view==='Calendar'&&<><div className="calendarlegend"><span>CONTENT PLAN</span>{staff.map(n=><span className="inline" key={n}><Avatar name={n}/>{n}</span>)}</div><div className="calendarscroll"><div className="calendar">{days.map(d=>{const date=d.toISOString().slice(0,10);return <section className="day" key={date}><div className="dayhead"><span>{d.toLocaleDateString('en',{weekday:'short'})}</span><strong>{d.getDate()}</strong></div>{filtered.filter(p=>p.date===date).map(p=><button onClick={()=>openPost(p)} className={'calendarpost '+(p.owners.length===1?p.owners[0].toLowerCase():'team')} key={p.id}><span className="inline"><Platform name={p.platform}/><small>{p.format}</small></span><strong>{p.title}</strong><span>{p.owners.length===3?'Team':p.owners.join(' & ')}</span><small>{p.status}</small></button>)}{!filtered.some(p=>p.date===date)&&<p className="dayempty">No posts planned</p>}{week==='2026-09-21'&&['2026-09-21','2026-09-23','2026-09-25'].includes(date)&&<div className="off">{date.endsWith('21')?'Elijah off':date.endsWith('23')?'Diana off*':'Reg off'}</div>}</section>})}</div></div><div className="plannotes"><strong>From the weekly plan</strong><p>Main output: same-day shoot and edit. Product showcases depend on product availability: montage, PC building, new arrivals, unboxing, customer builds and before/after setups. Static posts depend on SKU releases and informative content.</p><small>Main output is mapped to TikTok; unspecified owners are assigned to Team. September 21–27 uses 2026. *Diana appears in the reference’s off-day notes but is not included in the three-person team.</small></div></>}
 {view==='Analytics'&&<><div className="notice"><Link2 size={18}/><div><strong>Manual analytics · automatic sync not connected</strong><span>Record metrics on published posts. Missing values are excluded; no platform data is being pulled automatically.</span></div></div><div className="statusgrid">{(['views','likes','comments','shares'] as const).map(k=><div className="stat" key={k}><span>Total {k}</span><strong>{published.some(p=>p[k]!==null)?fmt(sum(k)):'—'}</strong><small>{published.filter(p=>p[k]!==null).length} posts with recorded data</small></div>)}</div><div className="twocol"><section className="panel"><div className="sectionhead"><h2>Views by platform</h2><span className="pill">Selected week</span></div><div className="barplot">{['Facebook','TikTok'].map(c=>{const rows=published.filter(p=>p.platform===c&&p.views!==null);const n=rows.reduce((s,p)=>s+(p.views??0),0);return <div key={c}><div className="memberrow"><span className="inline"><Platform name={c}/>{c}</span><strong>{rows.length?fmt(n):'No data'}</strong></div><div className="bigbar"><span style={{width:(sum('views')?n/sum('views')*100:0)+'%'}}/></div></div>})}</div></section><section className="panel"><div className="sectionhead"><h2>Engagement rate</h2></div><div className="engagement"><strong>{(()=>{const complete=published.filter(p=>[p.views,p.likes,p.comments,p.shares].every(v=>v!==null));const views=complete.reduce((s,p)=>s+p.views!,0);return views?((complete.reduce((s,p)=>s+p.likes!+p.comments!+p.shares!,0)/views)*100).toFixed(1)+'%':'—'})()}</strong><p>(Likes + comments + shares) ÷ views.<br/>Only posts with all four metrics are included.</p></div></section></div><section className="panel"><div className="sectionhead"><h2>Published content</h2><p>Select a post to update its metrics</p></div>{table(published)}</section></>}
 {view==='Team KPI'&&<><div className="team-management">{isAdmin&&<button className="primary" onClick={addStaff}><Plus size={18}/> Add staff</button>}</div>{staff.length?<div className="teamcards">{staff.map(name=>{const k=memberKpi(name);const rate=Math.round(k.weekly);return <section className="panel kpicard" key={name}><Avatar name={name}/><h2>{name}</h2><p>Digital Marketing</p><div className="ring" style={{background:'conic-gradient(#e3662b '+rate+'%, #f0f0f2 0)'}}><span>{rate}<small>% weekly KPI</small></span></div><div className="kpirow"><span>Selected week</span><strong>{range}</strong></div><div className="kpirow"><span>Requirements met</span><strong>{k.done} / {k.requirements}</strong></div><div className="kpirow"><span>Published posts</span><strong>{k.published}</strong></div><div className="kpirow"><span>Assigned posts</span><strong>{k.assigned}</strong></div><div className="kpirow"><span>In progress / review</span><strong>{inWeek.filter(p=>p.owners.includes(name)&&['In progress','For review'].includes(p.status)).length}</strong></div><div className="kpi-actions"><button className="secondary" onClick={()=>{setPerson(name);setPlatform('All platforms');setQuery('');setView('Posting Monitoring')}}>View assignments <ArrowRight size={16}/></button>{isAdmin&&<button className="secondary danger" onClick={()=>removeStaff(name)}>Remove staff</button>}</div></section>})}</div>:<div className="empty panel">No active staff. Add a staff member to start tracking KPI.</div>}<div className="plannotes"><strong>How team KPI is calculated</strong><p>Weekly KPI = completed requirements ÷ 3 × 100%. Every active staff member needs one published Facebook post, one published TikTok post, and one published Static post in the selected week.</p></div></>}
 </>}<footer><span>PC HUB <b>MARKETING</b></span><span>Shared workspace · {posts.length} content records</span></footer></main></div>
 <dialog ref={dialog} onCancel={e=>{if(saving)e.preventDefault();else setEdit(null)}}><form onSubmit={save}>{edit&&<><div className="sectionhead"><div><h2>{posts.some(p=>p.id===edit.id)?'Edit post':'Add post'}</h2></div><button type="button" aria-label="Close" onClick={()=>setEdit(null)} disabled={saving}><X size={20}/></button></div><div className="formbody"><label>Content title<input autoFocus required maxLength={200} value={edit.title} onChange={e=>setEdit({...edit,title:e.target.value})}/></label><div className="formgrid"><label>Platform<select value={edit.platform} onChange={e=>setEdit({...edit,platform:e.target.value})}>{['Facebook','TikTok'].map(x=><option key={x}>{x}</option>)}</select></label><label>Content type<select value={edit.contentType} onChange={e=>setEdit({...edit,contentType:e.target.value})}>{contentTypes.map(x=><option key={x}>{x}</option>)}</select></label><label>Posting date<input type="date" required value={edit.date} onChange={e=>setEdit({...edit,date:e.target.value})}/></label><label>Posting time<input type="time" value={edit.postedTime} onChange={e=>setEdit({...edit,postedTime:e.target.value})}/></label><label>Status<select value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value})}>{statuses.map(x=><option key={x}>{x}</option>)}</select></label></div><fieldset><legend>Posted by</legend>{staff.map(n=><label className="check" key={n}><input type="checkbox" checked={edit.owners.includes(n)} onChange={e=>setEdit({...edit,owners:e.target.checked?[...edit.owners,n]:edit.owners.filter(x=>x!==n)})}/><Avatar name={n}/>{n}</label>)}</fieldset><label>Post link<input type="url" placeholder="Paste the Facebook or TikTok link" value={edit.url} onChange={e=>setEdit({...edit,url:e.target.value})}/></label>{edit.url&&<a className="linkpreview" href={edit.url} target="_blank" rel="noreferrer"><span className="inline"><Platform name={edit.platform}/><strong>{edit.platform} post preview</strong></span><span>{edit.title||'Untitled content'} · {edit.contentType}</span><ArrowUpRight size={17}/></a>}{message&&<div className="error" role="alert">{message}</div>}</div><div className="formfooter"><button className="secondary" type="button" disabled={saving} onClick={()=>setEdit(null)}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':'Save post'}<Check size={17}/></button></div></>}</form></dialog></div>
}



